apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: acrmicroapp.azurecr.io/order-service:v1
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microapp
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
  - port: 8081
    targetPort: 8081
